language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
  - chmod +x $HOME/miniconda.sh
  - $HOME/miniconda.sh -b -f -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - wget https://github.com/nansencenter/sea_ice_drift_test_files/blob/master/S1A_EW_GRDM_1SDH_20161005T142446_20161005T142546_013356_0154D8_C3EC.SAFE.tif?raw=true -O S1A_EW_GRDM_1SDH_20161005T142446_20161005T142546_013356_0154D8_C3EC.SAFE.tif
  - wget https://github.com/nansencenter/sea_ice_drift_test_files/blob/master/S1B_EW_GRDM_1SDH_20161005T101835_20161005T101935_002370_004016_FBF1.SAFE.tif?raw=true -O S1B_EW_GRDM_1SDH_20161005T101835_20161005T101935_002370_004016_FBF1.SAFE.tif
  - export ICE_DRIFT_TEST_DATA_DIR=./

install:
  - conda create -q --yes -n test-environment -c conda-forge python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib netcdf4 gdal opencv nose coverage
  - source activate test-environment
  - python setup.py install

script:
  - coverage run --source=sea_ice_drift --omit=sea_ice_drift/tests.py setup.py test


